export const APP_WRITE_ID = '664743b30015e75ba3f5'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_COMMENTS = 'comments'
export const COLLECTION_CUSTOMERS = 'customers'
export const STORAGE_ID = 'storage'